### ISSUE TITLE
Add MGWR model to the program

### ISSUE THREAD

**Issue by TAOZI2022** [sunkun1997/mgtwr#1]
Including the mgwr (multiscale geographically weighted regression) model in the program will make users more easier to compare GWR-related modes' results.

**Comment by sunkun1997** [comment]
@TAOZI2022 I have added the MGWR model into the mgtwr package. You can fit MGWR model via ```pip install mgtwr==2.0.1``` now. If necessary, you can read "jupyter notebook"/example.ipynb to know how to use it.

**Comment by TAOZI2022** [comment]
Thank you so much for your work, and the added MGWR model works fine.
