### ISSUE TITLE
调用MGTWR.fit时，长时间未出结果

### ISSUE THREAD

**Issue by TongCWei** [sunkun1997/mgtwr#10]
我的数据量比较大，修改成最新的model.py运行下列两行代码，花费4h
sel_multi = SearchMGTWRParameter(c1, t1, X1, y1, kernel='bisquare', fixed=True,thread=12)
bws = sel_multi.search(multi_bw_min=[0.25], multi_bw_max=[2],verbose=True, tol_multi=1.0e-4, time_cost=True)
但在调用MGTWR.fit时，花费了一天半的时间，也没有出结果
mgtwr1 = MGTWR(c1, t1, X1, y1, sel_multi, kernel='bisquare', fixed=True).fit()
print(mgtwr1.R2)
刚开始运行这段代码时，cpu和内存占用都很高，但是经过一段时间后，cpu占用极低，内存占用也大幅度降低，但运行依旧未结束。
（另外想请教老师，ENP_j有效参数数具体是什么含义吗）

**Comment by sunkun1997** [comment]
运行结果有日志吗？是报超内存的错了吗?

**Comment by TongCWei** [comment]
没有报错，一直在运行，但是似乎并未调用计算机资源，运行结果一直没出来

**Comment by sunkun1997** [comment]
你是怎么运行的？你光这么说，我也不知道是什么情况

**Comment by TongCWei** [comment]
找到原因了 ，可能是内存问题导致了后台内核中断，感谢老师答疑。另外想请教老师，ENP_j有效参数数具体是什么含义吗

**Comment by sunkun1997** [comment]
衡量模型的复杂度

**Comment by sunkun1997** [comment]
mgtwr的fit方法可以传一个参数n_chunks分步计算，越大占用内存越小

**Comment by TongCWei** [comment]
感谢老师耐心解答！

**Comment by keyizhang-lxf** [comment]
你好，可以进一步交流一下mgtwr模型么
