### ISSUE TITLE
关于使用cupy库进行GPU计算的加速and .fit()的数据量较大讨论

### ISSUE THREAD

**Issue by hjjhh6** [sunkun1997/mgtwr#11]
孙老师 你好
经过近日实践调整，在本人数据为94万行，x为6列的情况下，运行主要时间花费在了model.py中 cal_aic的计算上

```
    def cal_aic(self):

        """
        use for calculating AICc, BIC, CV and so on.
        """
        if self.thread > 1:
            result = list(zip(*Parallel(n_jobs=self.thread)(delayed(self._search_local_fit)(i) for i in range(self.n))))
        else:
            result = list(zip(*map(self._search_local_fit, range(self.n))))
        err2 = np.array(result[0]).reshape(-1, 1)
        hat = np.array(result[1]).reshape(-1, 1)
        aa = np.sum(err2 / ((1 - hat) ** 2))
        RSS = np.sum(err2)
        tr_S = np.sum(hat)
        llf = -np.log(RSS) * self.n / 2 - (1 + np.log(np.pi / self.n * 2)) * self.n / 2

        return CalAicObj(tr_S, float(llf), float(aa), self.n)
```
在进程数thread=20的情况下，cal_aic调用10次，每次完成944655次并行任务平均耗时670min，然而依然未完成一次大迭代，即`print("Current iteration:", iter_num, ",SOC:", np.round(score, 7))
            print("Bandwidths:", ', '.join([str(bw) for bw in bws]))
            print("taus:", ','.join([str(tau) for tau in taus]))`
这是过于漫长的时长了，很大程度的限制了程序的运行，但分析函数本身完全可以使用GPU进行进一步加速，我曾经尝试过但是由于各个函数之间引用较多，加之我个人能力不足，较难完成该项工作，希望能优化该部分代码提供GPU加速选项。

**Comment by sunkun1997** [comment]
你可以提供一个未完成的demo吗？

**Comment by hjjhh6** [comment]
https://github.com/hjjhh6/mgtwr_learn.git 其中的gpudemo branch是我尝试的对象，但可以说基本上是失败的，主要问题在于

1. 函数调用太复杂，水平有限，不确定怎么修改；
2. kernel.py中```
def cal_distance(
            self,
            i: int):

        if self.tau == 0:
            self.coords_new = np.ndarray(self.coords)
        else:
            self.coords_new = np.hstack([np.ndarray(self.coords), (np.sqrt(self.tau) * np.ndarray(self.t))])
        distance = np.linalg.norm([self.coords_new[i]], self.coords_new).reshape(-1)
        return distance
```
在调用了该函数后，报错报告生成了self.n维矩阵，在我的数据中为944655维，cupy最多32维；

3. cupy不支持axis的设置；

**Comment by sunkun1997** [comment]
但是这里限制性能的不是矩阵计算，而是每一个观测点都需要进行矩阵运算，也就是矩阵运算的次数太多而不是单次计算时间太长

**Comment by hjjhh6** [comment]
明白了，可能cython才是更好的选择，但这也太难了

**Comment by hjjhh6** [comment]
> 但是这里限制性能的不是矩阵计算，而是每一个观测点都需要进行矩阵运算，也就是矩阵运算的次数太多而不是单次计算时间太长

或者一次输入多个观测点进行计算，使数据点大小达到百万size以上，应该能实现cupy带来的GPU加速，另一方面，保存distance的变量避免每次重新计算应该也会获得加速。

**Comment by hjjhh6** [comment]
孙老师 元旦快乐
这次我尝试将数据集逐年进行运算以避免数据集过大导致的cal_aic的n（数据倍率）^2的计算量上升，解决了时间过长的问题；
数据集现在下降到了39915行（其中2002年不包括1-3月，每月4435空间位置）；
MGTWR.fit()调用时，出现了memory error的情况，观察可发现是由于内存占用过大导致的，预计将生成88g以上的变量；
```
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
Cell In[12], [line 1](vscode-notebook-cell:?execution_count=12&line=1)
----> [1](vscode-notebook-cell:?execution_count=12&line=1) mgtwr = MGTWR(coords, t, X, y, sel_multi, kernel='gaussian', fixed=True).fit(n_chunks=1)
      [2](vscode-notebook-cell:?execution_count=12&line=2) print(mgtwr.R2)

File [e:\Gitsave\mgtwr_learn\mgtwr\model.py:675](file:///E:/Gitsave/mgtwr_learn/mgtwr/model.py:675), in MGTWR.fit(self, n_chunks)
    [673](file:///E:/Gitsave/mgtwr_learn/mgtwr/model.py:673) pre = np.sum(self.X * self.betas, axis=1).reshape(-1, 1)
    [674](file:///E:/Gitsave/mgtwr_learn/mgtwr/model.py:674) result = map(self._chunk_compute, (range(n_chunks)))
--> [675](file:///E:/Gitsave/mgtwr_learn/mgtwr/model.py:675) result_list = list(zip(*result))
    [676](file:///E:/Gitsave/mgtwr_learn/mgtwr/model.py:676) ENP_j = np.sum(np.array(result_list[0]), axis=0)
    [677](file:///E:/Gitsave/mgtwr_learn/mgtwr/model.py:677) CCT = np.sum(np.array(result_list[1]), axis=0)

File [e:\Gitsave\mgtwr_learn\mgtwr\model.py:630](file:///E:/Gitsave/mgtwr_learn/mgtwr/model.py:630), in MGTWR._chunk_compute(self, chunk_id)
    [628](file:///E:/Gitsave/mgtwr_learn/mgtwr/model.py:628) init_pR = np.zeros((n, len(chunk_index)))
    [629](file:///E:/Gitsave/mgtwr_learn/mgtwr/model.py:629) init_pR[chunk_index, :] = np.eye(len(chunk_index))
--> [630](file:///E:/Gitsave/mgtwr_learn/mgtwr/model.py:630) pR = np.zeros((n, len(chunk_index),
    [631](file:///E:/Gitsave/mgtwr_learn/mgtwr/model.py:631)                k))  # partial R: n by chunk_size by k
    [633](file:///E:/Gitsave/mgtwr_learn/mgtwr/model.py:633) for i in range(n):
    [634](file:///E:/Gitsave/mgtwr_learn/mgtwr/model.py:634)     wi = self._build_wi(i, self.bw, self.tau).reshape(-1, 1)

MemoryError: Unable to allocate 83.1 GiB for an array with shape (39915, 39915, 7) and data type float64
```
虽然该问题可以手动通过手动设置n_chunks得到解决，但建议n_chunks的设定给予一个基于电脑内存上限的数值以保证不会出现该错误。

**Comment by hjjhh6** [comment]
> 孙老师 元旦快乐 这次我尝试将数据集逐年进行运算以避免数据集过大导致的cal_aic的n（数据倍率）^2的计算量上升，解决了时间过长的问题; 数据集现在下降到了39915行（其中2002年不包括1-3月，每月4435空间位置）; MGTWR.fit（）调用时，出现了memory error的情况，观察可发现是由于内存占用过大导致的，预计将生成88g以上的变量;
> 
> ```
> ---------------------------------------------------------------------------
> MemoryError                               Traceback (most recent call last)
> Cell In[12], [line 1](vscode-notebook-cell:?execution_count=12&line=1)
> ----> [1](vscode-notebook-cell:?execution_count=12&line=1) mgtwr = MGTWR(coords, t, X, y, sel_multi, kernel='gaussian', fixed=True).fit(n_chunks=1)
>       [2](vscode-notebook-cell:?execution_count=12&line=2) print(mgtwr.R2)
> 
> File [e:\Gitsave\mgtwr_learn\mgtwr\model.py:675](file:///E:/Gitsave/mgtwr_learn/mgtwr/model.py:675), in MGTWR.fit(self, n_chunks)
>     [673](file:///E:/Gitsave/mgtwr_learn/mgtwr/model.py:673) pre = np.sum(self.X * self.betas, axis=1).reshape(-1, 1)
>     [674](file:///E:/Gitsave/mgtwr_learn/mgtwr/model.py:674) result = map(self._chunk_compute, (range(n_chunks)))
> --> [675](file:///E:/Gitsave/mgtwr_learn/mgtwr/model.py:675) result_list = list(zip(*result))
>     [676](file:///E:/Gitsave/mgtwr_learn/mgtwr/model.py:676) ENP_j = np.sum(np.array(result_list[0]), axis=0)
>     [677](file:///E:/Gitsave/mgtwr_learn/mgtwr/model.py:677) CCT = np.sum(np.array(result_list[1]), axis=0)
> 
> File [e:\Gitsave\mgtwr_learn\mgtwr\model.py:630](file:///E:/Gitsave/mgtwr_learn/mgtwr/model.py:630), in MGTWR._chunk_compute(self, chunk_id)
>     [628](file:///E:/Gitsave/mgtwr_learn/mgtwr/model.py:628) init_pR = np.zeros((n, len(chunk_index)))
>     [629](file:///E:/Gitsave/mgtwr_learn/mgtwr/model.py:629) init_pR[chunk_index, :] = np.eye(len(chunk_index))
> --> [630](file:///E:/Gitsave/mgtwr_learn/mgtwr/model.py:630) pR = np.zeros((n, len(chunk_index),
>     [631](file:///E:/Gitsave/mgtwr_learn/mgtwr/model.py:631)                k))  # partial R: n by chunk_size by k
>     [633](file:///E:/Gitsave/mgtwr_learn/mgtwr/model.py:633) for i in range(n):
>     [634](file:///E:/Gitsave/mgtwr_learn/mgtwr/model.py:634)     wi = self._build_wi(i, self.bw, self.tau).reshape(-1, 1)
> 
> MemoryError: Unable to allocate 83.1 GiB for an array with shape (39915, 39915, 7) and data type float64
> ```
> 
> 虽然该问题可以手动通过手动设置n_chunks得到解决，但建议n_chunks的设定给予一个基于电脑内存上限的数值以保证不会出现该错误。

另一方面，该部分应该也可以使用并行处理

**Comment by sunkun1997** [comment]
一般而言不太会考虑内存问题。程序里不止这一个变量，计算机也可能会有其他占用内存的进程，所以内存的上限需要根据用户的行为来界定，这不具备一般性。这里可以并行，但通常这个数字不会太大，运算次数也不多，多进程带来的收益不明显

**Comment by hjjhh6** [comment]
> 一般而言不太会考虑内存问题。程序里不止这一个变量，计算机也可能会有其他占用内存的进程，所以内存的上限需要根据用户的行为来界定，这不具备一般性。这里可以并行，但通常这个数字不会太大，运算次数也不多，多进程带来的收益不明显

孙老师，由于chunk设置了4435（即每一个chunk含有213个数据点）后依然在较短时间内没有跑出结果，因此我尝试使用了joblib库进行并行.fit

```
def fit(self, n_chunks=1):
    """
    Compute MGTWR inference by chunk to reduce memory footprint.
    """
    self.n_chunks = n_chunks
    pre = np.sum(self.X * self.betas, axis=1).reshape(-1, 1)

    result = Parallel(n_jobs=-1)(delayed(self._chunk_compute)(i) for i in range(n_chunks))

    result_list = list(zip(*result))
    ENP_j = np.sum(np.array(result_list[0]), axis=0)
    CCT = np.sum(np.array(result_list[1]), axis=0)
    return MGTWRResults(
        self.coords, self.t, self.X, self.y, self.bws, self.taus, self.kernel, self.fixed, self.bw_ts,
        self.bws_history, self.taus_history, self.betas, pre, ENP_j, CCT)
```

chunk设置为50，即大部分为798左右，并行设置为6，然而完成第一次6个并行任务即6个chunk花费时间为314min，后续总时间到800min+，即第二组6个任务花费了400+min尚未跑完，是否可能和 #10 提到的问题有相关？

**Comment by hjjhh6** [comment]
孙老师，经运行1200min检验，主要耗时为ENP_j和CCT计算，有多个chunk后，每个chunk都得执行self.n次计算，时间较长，但更长的是`for iter_i in range(self.bws_history.shape[0]): `之后的计算，建议fit添加输入参数skip_calculation，为该情况时候返回MGWRResults类相关参数为None,跳过相关参数运算，仅保留R2、beta和reside。考虑到论文中指出的AICc在MGTWR方法中多带宽比较的讨论，这在一定程度上应该是可以接受的。

> Moreover, allowing different bandwidths for each relationship could render the usual form of the AICc meaningless. Therefore, future research will focus on constructing local equivalents with coefficients of determination, standard errors, and t statistics (Fotheringham et al. 2017). 
Wu, Chao & Ren, Fu & Hu, Wei & Du, Qingyun. (2018). Multiscale geographically and temporally weighted regression: exploring the spatiotemporal determinants of housing prices. International Journal of Geographical Information Science. 33. 1-23. 10.1080/13658816.2018.1545158.

**Comment by sunkun1997** [comment]
> 孙老师，经运行1200min检验，主要耗时为ENP_j和CCT计算，有多个chunk后，每个chunk都得执行self.n次计算，时间较长，但更长的是`for iter_i in range(self.bws_history.shape[0]): `之后的计算，建议fit添加输入参数skip_calculation，为该情况时候返回MGWRResults类相关参数为None,跳过相关参数运算，仅保留R2、beta和reside。考虑到论文中指出的AICc在MGTWR方法中多带宽比较的讨论，这在一定程度上应该是可以接受的。
> 
> > Moreover, allowing different bandwidths for each relationship could render the usual form of the AICc meaningless. Therefore, future research will focus on constructing local equivalents with coefficients of determination, standard errors, and t statistics (Fotheringham et al. 2017).
> > Wu, Chao & Ren, Fu & Hu, Wei & Du, Qingyun. (2018). Multiscale geographically and temporally weighted regression: exploring the spatiotemporal determinants of housing prices. International Journal of Geographical Information Science. 33. 1-23. 10.1080/13658816.2018.1545158.

跳过_chunk_compute的计算吗？

**Comment by hjjhh6** [comment]
> > 孙老师，经运行1200min检验，主要耗时为ENP_j和CCT计算，有多个chunk后，每个chunk都得执行self.n次计算，时间较长，但更长的是之后的计算，建议fit添加输入参数skip_calculation，为该情况时候返回MGWRResults类相关参数为None，跳过相关参数运算，仅保留R2、beta和reside。考虑到论文中指出的AICc在MGTWR方法中多带宽比较的讨论，这在一定程度上应该是可以接受的。`for iter_i in range(self.bws_history.shape[0]): `
> > > 此外，允许每种关系使用不同的带宽可能会使通常形式的 AICc 变得毫无意义。因此，未来的研究将侧重于构建具有决定系数、标准误差和 t 统计量的局部等价物（Fotheringham 等人，2017 年）。 Wu， Chao & 任， Fu & 胡， Wei & Du， Qingyun.（2018）. 多尺度地理和时间加权回归：探索房价的时空决定因素.国际地理信息科学杂志.33. 1-23.10.1080/13658816.2018.1545158.
> 
> 跳过_chunk_compute的计算吗？

是的，我实验过应该是可行的，因为我更关注beta和R2，函数的拟合同样也在之前的迭代SOC使用平滑函数给了评估。而ENP_j和CCT返回到`class MGWRResults(BaseModel)`中的值应该可以跳过。我明白返回的参数对于度量模型的重要性，但是R2已经可以作为一个可行的度量标准，在大数据情况下，再使用更多度量模型拟合的参数，计算量所耗费时间是明显过大的。

**Comment by sunkun1997** [comment]
> > > 孙老师，经运行1200min检验，主要耗时为ENP_j和CCT计算，有多个chunk后，每个chunk都得执行self.n次计算，时间较长，但更长的是之后的计算，建议fit添加输入参数skip_calculation，为该情况时候返回MGWRResults类相关参数为None，跳过相关参数运算，仅保留R2、beta和reside。考虑到论文中指出的AICc在MGTWR方法中多带宽比较的讨论，这在一定程度上应该是可以接受的。`for iter_i in range(self.bws_history.shape[0]): `
> > > > 此外，允许每种关系使用不同的带宽可能会使通常形式的 AICc 变得毫无意义。因此，未来的研究将侧重于构建具有决定系数、标准误差和 t 统计量的局部等价物（Fotheringham 等人，2017 年）。 Wu， Chao & 任， Fu & 胡， Wei & Du， Qingyun.（2018）. 多尺度地理和时间加权回归：探索房价的时空决定因素.国际地理信息科学杂志.33. 1-23.10.1080/13658816.2018.1545158.
> > 
> > 
> > 跳过_chunk_compute的计算吗？
> 
> 是的，我实验过应该是可行的，因为我更关注beta和R2，函数的拟合同样也在之前的迭代SOC使用平滑函数给了评估。而ENP_j和CCT返回到`class MGWRResults(BaseModel)`中的值应该可以跳过。我明白返回的参数对于度量模型的重要性，但是R2已经可以作为一个可行的度量标准，在大数据情况下，再使用更多度量模型拟合的参数，计算量所耗费时间是明显过大的。

嗯，可以的

**Comment by hjjhh6** [comment]
孙老师，另建议在model.py处修改并行代码为`list(zip(*Parallel(n_jobs=self.thread,pre_dispatch='all',batch_size=self.n//self.thread)`，该修改将使所有任务在一开始分配给所有worker，节省通信时间，经实验，在53220行6个自变量的情况下，一次cal_aic的运行时间从2.1min减小为1.6min，为原始时间的76.2%,考虑到在不进行优化的情况下经过了5000min的迭代，大部分时间为cal_aic，这一修改将进一步节省大量的时间，且并没有导致内存溢出或更高的内存占用（16G为64%），相关文件后续上传

**Comment by hjjhh6** [comment]
#12 model.py的修改，进一步适合大数据量的情况

**Comment by hjjhh6** [comment]
正在进行下一次任务，等我跑完给出结果吧孙老师，确保不会导致大数据情况下出其他内存溢出的bug。

**Comment by hjjhh6** [comment]
在X为53220*6的情况下已尝试3次迭代，确保了可进行迭代：
`Current iteration: 1 ,SOC: 0.0092011
Bandwidths: 1.1, 39.9, 3.7, 29.9, 1.1, 6.9, 1.6
taus: 1.4,10.1,0.5,10.1,1.9,2.9,0.6
Current iteration: 2 ,SOC: 0.0070699
Bandwidths: 1.1, 39.9, 2.8, 26.5, 1.1, 5.0, 1.4
taus: 1.6,10.1,1.2,10.1,1.9,2.7,0.8
Current iteration: 3 ,SOC: 0.005994
Bandwidths: 1.1, 39.9, 2.4, 13.5, 1.1, 2.1, 1.3
taus: 1.6,10.1,1.5,10.1,1.9,0.5,0.8`
数据为example，thread=5，且以上迭代未停止，
优化后 3分54.1s 完成8次迭代，优化后 超过10分钟 仅完成1次迭代（未迭代完成），
以上结果可说明稳定性及加速情况，建议再次单独环境情况下尝试对比。
