### ISSUE TITLE
如何查看每个影响因子的回归系数

### ISSUE THREAD

**Issue by HeyAy** [sunkun1997/mgtwr#13]
GWR拟合后只能查看influ这一个监测结果

**Comment by sunkun1997** [comment]
https://github.com/sunkun1997/mgtwr/blob/5680ee85d6f010a9f34c3d611c51d95a9938c4db/mgtwr/model.py#L68C9-L83C74
print(gwr.betas)就可以

**Comment by HeyAy** [comment]
非常感谢，我再仔细的学习一下mgtwr中其他参数的调用

**Comment by keyizhang-lxf** [comment]
你好呀，可以交流一下mgtwr模型么
