### ISSUE TITLE
关于将已知的带宽值传入MGTWR.fit模型的问题~

### ISSUE THREAD

**Issue by Lyy0501** [sunkun1997/mgtwr#14]
孙老师好，看到您在示例文件中有关于将已知的带宽值传入MGTWR.fit模型的描述：如下：
class sel_multi:
    def __init__(self, bws):
        self.bws = bws

        
selector = sel_multi(bws)
mgtwr = MGTWR(coords, t, X, y, selector, kernel='gaussian', fixed=True).fit()
但是MGTWR需要bws和taus两组参数，要怎么设置呢？我尝试下面方法：（数字是我自己随便定的哈）
class sel_multi:
    def __init__(self, bws, taus):
        self.bws = bws
        self.taus = taus

# 定义带宽和时间比例的数值
custom_bws = [0.9, 0.7, 0.5]
custom_taus = [3.6, 0.2, 0.8]

# 使用自定义选择器类初始化选择器
custom_selector = sel_multi(bws=custom_bws, taus=custom_taus)

# 将自定义选择器传递给 MGTWR 模型
mgtwr = MGTWR(coords, t, X, y, selector=custom_selector, kernel='gaussian', fixed=True).fit()
会报错： list index out of range
所以求问这个具体是要怎么传入已知的bws和taus呀？谢谢~

**Comment by sunkun1997** [comment]
#6 参考这个issue  https://github.com/sunkun1997/mgtwr/issues/6#issuecomment-1845223015

**Comment by Lyy0501** [comment]
好嘞 谢谢~

**Comment by Lyy0501** [comment]
对了，还想问一下孙老师，每次迭代出来的bw和tau的值的个数为啥是比特征的数量多一个呢？不是很理解这里~

**Comment by sunkun1997** [comment]
有一列常数项，可以用constant参数控制

**Comment by Lyy0501** [comment]
好嘞，谢谢~~还想问下MGTWR.fit函数中，参数fixed=True的时候，这个模型是否和GTWR类似，带宽的大小在所有空间点和时间点上都是固定的，不会随着数据的空间位置或时间而变化了呢？

**Comment by sunkun1997** [comment]
是的

**Comment by Lyy0501** [comment]
好嘞~谢谢孙老师，祝春节快乐~
