### ISSUE TITLE
寻找gtwr最佳带宽时提示Matrix is singular.

### ISSUE THREAD

**Issue by HeyAy** [sunkun1997/mgtwr#15]
孙老师您好，我将自己的数据集标准化后进行处理，在寻找最佳时空带宽时提示：Matrix is singular.
我想询问一下这个原因是否是空气污染物数据集存在过大的异常值，然后再标准化后数据分布过偏、非正态分布导致的结果

**Comment by sunkun1997** [comment]
奇异矩阵是一个常见以及棘手的问题，起因是距离过近带宽太小导致权重矩阵近似为0，可以尝试提高带宽的最小阈值

**Comment by HeyAy** [comment]
非常感谢您的帮助，我还有一个问题是，我的样本是117个，时间是366天，我尝试设置阈值后，优选出来的bw和tau均为0.4，这个结果是可信的吗

**Comment by sunkun1997** [comment]
可以，这两个参数没有什么联系

**Comment by sunkun1997** [comment]
https://github.com/sunkun1997/mgtwr/issues/2#issuecomment-1256896345  参考这个issue
