### ISSUE TITLE
关于未采样点因变量值预测的问题

### ISSUE THREAD

**Issue by Lyy0501** [sunkun1997/mgtwr#16]
孙老师好，我想再问一下除了预测已采样点（即同时有自变量与因变量观测数据）的因变量值以外，MGTWR库里面是否可以预测未采样点（即只有自变量没有因变量观测值）的因变量值呢？我翻了原始代码似乎没有这一块的？不知道是不是我漏掉了~谢谢您

**Comment by sunkun1997** [comment]
关于局部加权模型的外推，目前还未有充分的理论依据，所以暂时没有这部分的代码

**Comment by Lyy0501** [comment]
好的，明白了，谢谢Thanks♪(･ω･)ﾉ
