### ISSUE TITLE
关于后续p值计算差异的问题（Questions about differences in subsequent p-value calculations.）

### ISSUE THREAD

**Issue by asoluer** [sunkun1997/mgtwr#17]
孙老师您好！我尝试了代码中的GTWR模型（已经对数据进行了投影，去除共线性和标准化等操作，点位提取方式按照各个行政区面中心提取），并将代码模型的结果与黄波教授团队开发的ArcGIS-GTWR插件结果进行了比较。发现虽然代码计算的r方值结果略优于GTWR插件，但是当我尝试计算p值并与插件的结果相比较发现，二者差异很大（参考使用输出的reside值和tvalues计算p值）。使用插件计算的结果能够完美通过p检验，而是用代码计算p值的结果则出现了多个变量不能通过检验。随后我尝试了计算MGTWR，仍然出现了这个问题（r方结果很好）。我想知道是代码参数设定问题还是我计算p值的方式有问题，如有错误理解和操作，恳请老师指教！
![GIS插件的参数设置](https://github.com/sunkun1997/mgtwr/assets/41777817/580af148-8c0e-4803-9058-2edb8e22fb9a)
![GIS插件的p值输出](https://github.com/sunkun1997/mgtwr/assets/41777817/2c1fa057-38dc-4eb3-b655-57edc3542892)
![使用代码计算p值输出](https://github.com/sunkun1997/mgtwr/assets/41777817/2caa7e52-0745-42d9-93a2-c6d91ab11c13)

这是我尝试计算p值的代码（忽略了截距的p值输出）：
import pandas as pd
from scipy.stats import t
import numpy as np

df_reside = pd.read_csv('gtwr_df_reside.csv')
tvalues = pd.read_csv('gtwr_tvalues.csv')
df_reside_value = df_reside.iloc[0, 0]
tvalues_no_intercept = tvalues.iloc[:, 1:]  

p_values_no_intercept = 2 * (1 - t.cdf(abs(tvalues_no_intercept), df_reside_value))
p_values_precise_no_intercept = np.round(p_values_no_intercept, 7) 
p_values_df_no_intercept = pd.DataFrame(p_values_precise_no_intercept)
p_values_df_no_intercept.to_csv('gtwr_p_values_precise_no_intercept.csv', index=False, header=False)

**Comment by sunkun1997** [comment]
用模型的自由度df_model呢？

**Comment by asoluer** [comment]
我查看了模型自由度为：df_model = 317.8377487285486,然后再次进行计算，发现结果一样：
![new](https://github.com/sunkun1997/mgtwr/assets/41777817/e8dfe091-e492-45c1-931f-0f201405e626)
![old](https://github.com/sunkun1997/mgtwr/assets/41777817/b4e728a7-b11e-45ef-95b0-4daf5c03e854)
没区别。
这是我的计算方式，不知道是否正确：
file_path = 'gtwr_tvalues.csv'
t_values_df = pd.read_csv(file_path)
# 给定自由度
df = 317.8377487285486
# 计算p值的函数
def calculate_p_values(t_values, df):
    # 对每个t值应用双侧p值计算公式
    p_values = t_values.applymap(lambda x: 2 * min(t.cdf(x, df), 1 - t.cdf(x, df)))
    return p_values
p_values_df = calculate_p_values(t_values_df, df)

**Comment by sunkun1997** [comment]
我找不到有什么错

**Comment by asoluer** [comment]
我很好奇，二者在拟合结果上并没有太大的差异，为何p值结果区别这么大。
![image](https://github.com/sunkun1997/mgtwr/assets/41777817/d6b35c9a-4ba6-42e8-9370-3bb531b88a16)

**Comment by sunkun1997** [comment]
p值的计算方式有所差异吧，这个插件的源码公开吗？

**Comment by asoluer** [comment]
没有在网上看见作者的源码，估计只能去研究下作者链接文章的计算方式了。我第一次接触相关的计算，我以为p值的计算方式是固定。
这是作者提供的插件：



------------------ 原始邮件 ------------------
发件人: sunkun1997 ***@***.***&gt;
发送时间: 2024年3月22日 17:52
收件人: sunkun1997/mgtwr ***@***.***&gt;
抄送: MIKE_L ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [sunkun1997/mgtwr] 关于后续p值计算差异的问题（Questions about differences in subsequent p-value calculations.） (Issue #17)





 
p值的计算方式有所差异吧，这个插件的源码公开吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
 
 	
 	 		 			从QQ邮箱发来的超大附件 	
 	 		 				 					 						 							 						 					
 					 						 							GTWR_AddIn.rar 							 (4.6MB, 无限期) 						 						 							进入下载页面 							：https://wx.mail.qq.com/ftn/download?func=3&k=cbc76f6370f5fa75f9b41e633b3536389b41796339353638111752010102040104081d56000c0515000e0402140d0608011503500c03055d035b510109533838736c67316674525c7d561e11584722d3bb7ba6df49d570f8f7dd30bc09e68e729eaa98&key=cbc76f6370f5fa75f9b41e633b3536389b41796339353638111752010102040104081d56000c0515000e0402140d0608011503500c03055d035b510109533838736c67316674525c7d561e11584722d3bb7ba6df49d570f8f7dd30bc09e68e729eaa98&code=480c9568&from=

**Comment by Ice2king** [comment]
reside不是残差吗，为啥能用作自由度第一个代码中
