### ISSUE TITLE
spatial bandwidth and temporal bandwidth questions about the model of GTWR and MGTWR in the python package mgtwr

### ISSUE THREAD

**Issue by yilvzhishi** [sunkun1997/mgtwr#2]
which api of mgtwr can show the GTWR and MGTWR's result of spatial bandwidth and temporal bandwidth?
Then when running the GTWR and MGTWR ,it shows bandwidths and taus ,my question is what is the tau(taus)?What is the meaning of it(tau,taus).
I advise you add an api of the GTWR and MGTWRresult diagnose report.Thank you !

**Comment by sunkun1997** [comment]
In this library, because of we can calculate temporal bandwidth bw_t  by 
$$bw_t = \sqrt{bw_s^2/\tau}$$
so we choose to search spatial bandwidth bw_s and tau. 
Bandwidths and taus are the corresponding spatial  bandwidth amd tau of all variables.

**Comment by sunkun1997** [comment]
In this library, because of we can calculate temporal bandwidth bw_t  by 
$$bw_t = \sqrt{bw_s^2/\tau}$$
so we choose to search spatial bandwidth bw_s and tau. 
Bandwidths and taus are the corresponding spatial  bandwidth amd tau of all variables.

**Comment by TongCWei** [comment]
tau是指时间带宽吗
