### ISSUE TITLE
关于mgtwr模型拟合R2过高的问题

### ISSUE THREAD

**Issue by chencc216** [sunkun1997/mgtwr#21]
sunkun老师，您好
      最近我在使用mgtwr模型进行拟合时，发现最后R2最后结果高达0.9993808951520635。我的数据是从2001年至2020年，一个因变量，三个解释变量。每一年都有212行数据。当我在mgtwr模型中，寻找最佳带宽时，模型会首先报错：D:\Anaconda3\Lib\site-packages\mgtwr\function.py:31: LinAlgWarning: Ill-conditioned matrix (rcond=9.72684e-18): result may not be accurate.
  xtx_inv_xt = linalg.solve(xtx, xt)
但之后它依旧正常运行。模型迭代了47次，运行时间为6.5h。模型的预测值也与真实值全都非常接近。最后出来的一些结果参数如下：
      RSS: 20.24229025568103
      ENP: 2631.099682933675
      tr_S: 2631.099682933675
      R2: 0.9993808951520635
      adj_R2: 0.9983678183140164
      aic: -5364.070786958312
      aic_c: 3250.041129944747
      bic: -10586.508560084532
      sigma2: 0.012581444630821443
      taus: [0.2 3.8 3.8 0.2]
      bws: [0.5 1.1 1.2 0.5]
      bw_ts: [1.11803399 0.56428809 0.61558701 1.11803399]
      我想请问您，这个我的结果是否可靠呢？或者您有什么建议，谢谢您的回复！

**Comment by sunkun1997** [comment]
那个不是报错，只是警告：带宽过小导致权重矩阵趋近于0；由于上述原因，模型过拟合，所以衡量模型好坏一般不用R2，用aic值更为合理

**Comment by chencc216** [comment]
感谢老师的回复，当我将内核改为bisquare，并将fixed从True改为False时，运行代码并没有发出警告，运行了2h，迭代20次完成了此次运算。
`sel_multi = SearchMGTWRParameter(coords, t, X, y, kernel='bisquare', fixed=False)`
`bws = sel_multi.search(multi_bw_min=[0.1], verbose=True, tol_multi=1.0e-4, time_cost=True)`
`mgtwr = MGTWR(coords, t, X, y, sel_multi, kernel='bisquare', fixed=False).fit()
print(mgtwr.R2)`
R2：       0.9969042273668183
adj_R2:   0.9942987912999741
aic:         72.50855922226083
aic_c:      3334.947448665798
对于此拟合结果，R2依旧较高，但aic值却很小。此外我使用示例数据在示例代码运行完成后，它的R2同样高达0.9973007654946879。我想请问您，此次运行没有发出警告，它的结果仍然可能是过拟合的吗？

**Comment by hjjhh6** [comment]
> 感谢老师的回复，当我将内核改为bisquare，并将fixed从True改为False时，运行代码并没有发出警告，运行了2h，迭代20次完成了此次运算。 `sel_multi = SearchMGTWRParameter(coords, t, X, y, kernel='bisquare', fixed=False)` `bws = sel_multi.search(multi_bw_min=[0.1], verbose=True, tol_multi=1.0e-4, time_cost=True)` `mgtwr = MGTWR(coords, t, X, y, sel_multi, kernel='bisquare', fixed=False).fit() print(mgtwr.R2)` R2： 0.9969042273668183 adj_R2: 0.9942987912999741 aic: 72.50855922226083 aic_c: 3334.947448665798 对于此拟合结果，R2依旧较高，但aic值却很小。此外我使用示例数据在示例代码运行完成后，它的R2同样高达0.9973007654946879。我想请问您，此次运行没有发出警告，它的结果仍然可能是过拟合的吗？

是否过拟合不能通过是否报错来进行判断，或者说是否过拟合只是一个概念而不是具有显著分析的方法，考虑到你的数据量级，你可以尝试着减去第一年或最后一年，看看是否带宽有存在显著变化，如果有，那么很有可能存在过拟合的情况。

另一方面，对于模型的解释性使用AIC和AICc判定时，该值为回归模型间的相对值，需要和其他回归模型进行比较，也即GTWR、GWR、OLS，更小的AIC或AICc表示模型更好。
