### ISSUE TITLE
如何结果显示MGTWR的回归系数

### ISSUE THREAD

**Issue by keyizhang-lxf** [sunkun1997/mgtwr#24]
孙老师您好，代码仅显示了R2，我看还能显示AICc，但是没有看到有显示回归系数的参数，我应该怎么操作呢

**Comment by sunkun1997** [comment]
调用betas attribute https://github.com/sunkun1997/mgtwr/blob/5680ee85d6f010a9f34c3d611c51d95a9938c4db/mgtwr/obj.py#L101

**Comment by keyizhang-lxf** [comment]
谢谢孙老师，已经解决啦
