### ISSUE TITLE
关于每个变量的空间带宽和时间带宽

### ISSUE THREAD

**Issue by keyizhang-lxf** [sunkun1997/mgtwr#25]
孙老师又再次打扰您了，bws和bw_ts是所有变量的空间带宽和时间带宽，可以有单个变量的空间带宽和时间带宽么，再次感谢老师！

**Comment by sunkun1997** [comment]
单个就是对应位置的索引

**Comment by keyizhang-lxf** [comment]
谢谢老师，跑出来啦，祝老师工作顺利、身体健康！

**Comment by iceberg7660** [comment]
> 单个就是对应位置的索引

不好意思孙老师，没看懂是什么意思
