### ISSUE TITLE
求大佬qq联系方式

### ISSUE THREAD

**Issue by soul-for-rice** [sunkun1997/mgtwr#4]
想找老哥请教一些mgtwr包的用法，例子不是很详细，例如GTWR模型结果怎么看

**Comment by taotianhui93** [comment]
你好，请问mgtwr的时间带宽的结果显示的很大，单位是秒吗

**Comment by DaQiAlbert** [comment]
> 想找老哥请教一些mgtwr包的用法，例子不是很详细，例如GTWR模型结果怎么看

请问您得到回复了吗？不知道怎么输出诊断报告，和局部的统计量

**Comment by soul-for-rice** [comment]
没有接着用这个包了，你可以直接找这个佬，我记得他的qq在setup.py上有




张荣祯
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sunkun1997/mgtwr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月3日(星期天) 上午10:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sunkun1997/mgtwr] 求大佬qq联系方式 (Issue #4)





  
想找老哥请教一些mgtwr包的用法，例子不是很详细，例如GTWR模型结果怎么看
  
请问您得到回复了吗？不知道怎么输出诊断报告，和局部的统计量

**Comment by sunkun1997** [comment]
> 想找老哥请教一些mgtwr包的用法，例子不是很详细，例如GTWR模型结果怎么看

调用GTWR.fit()方法以后返回GTWRResults实例，你可以输入help(GTWRResults)获取其中的属性及其帮助，例如gtwr.tvalues获取t统计量的值

**Comment by sunkun1997** [comment]
> 你好，请问mgtwr的时间带宽的结果显示的很大，单位是秒吗

根据你的输入决定
