### ISSUE TITLE
老师您好，如何输出诊断报告和局部的统计量和R2，P值等参数呢

### ISSUE THREAD

**Issue by DaQiAlbert** [sunkun1997/mgtwr#6]
老师您好，如何输出诊断报告和局部的统计量和R2，P值等参数呢

**Comment by sunkun1997** [comment]
> 老师您好，如何输出诊断报告和局部的统计量和R2，P值等参数呢

调用模型的fit()方法以后返回相应的Results，输入help获取相应的帮助。结果给出了t统计值和R2，P值可以自己计算得出

**Comment by DaQiAlbert** [comment]
谢谢老师。如果老师有空将每个区域的回归系数写入代码里，我相信mgtwr将会得到更多、更广泛的应用。

**Comment by sunkun1997** [comment]
> 谢谢老师。如果老师有空将每个区域的回归系数写入代码里，我相信mgtwr将会得到更多、更广泛的应用。

回归系数是有的，就是betas

**Comment by DaQiAlbert** [comment]
> > 谢谢老师。如果老师有空将每个区域的回归系数写入代码里，我相信mgtwr将会得到更多、更广泛的应用。
> 
> 回归系数是有的，就是betas

请问：如果是2个X，则有3列和回归系数，请问哪一列是常量，哪一列是X1，或者X2，这个是如何排列的呢？

**Comment by DaQiAlbert** [comment]
![微信图片_20231205224109](https://github.com/sunkun1997/mgtwr/assets/127284843/d7a735f8-d97e-487f-a3c5-26496d65594c)
（使用的是老师的示例代码

**Comment by sunkun1997** [comment]
> > > 谢谢老师。如果老师有空将每个区域的回归系数写入代码里，我相信mgtwr将会得到更多、更广泛的应用。
> > 
> > 
> > 回归系数是有的，就是betas
> 
> 请问：如果是2个X，则有3列和回归系数，请问哪一列是常量，哪一列是X1，或者X2，这个是如何排列的呢？

根据输入的X决定，默认的常量是放在第一列的，所以这里第一列是常量的系数

**Comment by liuqi0314** [comment]
好的，谢谢孙老师，那么如何对您进行引用呢

**Comment by DaQiAlbert** [comment]
![image](https://github.com/sunkun1997/mgtwr/assets/127284843/d702219a-ce15-4d13-9b38-dc8cf32f1a95)
孙老师，如果我有两个自变量已知带宽的话，比如空间是1.5，1.5，时间带宽是2.8，2.8。那么应如何将带宽输入给bws，应该怎么写入呢？另外，MGTWR模型，比如bw_s是8，tau是2，那么依据公式，bw_t=根号（8^2/2）=32，我的理解对吗？最后，老师我该如何对您进行引用呢？

**Comment by sunkun1997** [comment]
> ![image](https://private-user-images.githubusercontent.com/127284843/288743244-d702219a-ce15-4d13-9b38-dc8cf32f1a95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NTAzMjAsIm5iZiI6MTcwMTk1MDAyMCwicGF0aCI6Ii8xMjcyODQ4NDMvMjg4NzQzMjQ0LWQ3MDIyMTlhLWNlMTUtNGQxMy05YjM4LWRjOGNmMzJmMWE5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwN1QxMTUzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OWQzODMzZDFmZjJlZmJmZWQyMzE3N2NiZjE3NGQwMmQxNjNlM2YxYWUyYzZmOGQ5ODAxYTRkMTVhYjFiNzk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2edmXYTGFhCqqWSw5VfzYwqMFmuza_tvseJFtSi7dLA) 孙老师，如果我有两个自变量已知带宽的话，比如空间是1.5，1.5，时间带宽是2.8，2.8。那么应如何将带宽输入给bws，应该怎么写入呢？另外，MGTWR模型，比如bw_s是8，tau是2，那么依据公式，bw_t=根号（8^2/2）=32，我的理解对吗？最后，老师我该如何对您进行引用呢？

你需要传入的是SearchMGTWRParameter.search()的返回值，即mgtwr.function.multi_bws的返回值，它有9个

**Comment by DaQiAlbert** [comment]
我那个模型跑的时间太久了，想直接用已迭代的最好结果。不知道应该如何写入。谢谢老师，太麻烦老师了

**Comment by DaQiAlbert** [comment]
> 我那个模型跑的时间太久了，想直接用已迭代的最好结果。不知道应该如何写入。谢谢老师，太麻烦老师了

从昨天20点 跑到今天19点 还没出结果，迭代了130多次

**Comment by sunkun1997** [comment]
> 我那个模型跑的时间太久了，想直接用已迭代的最好结果。不知道应该如何写入。谢谢老师，太麻烦老师了

不可以，模型的结果依赖搜索的历史

**Comment by DaQiAlbert** [comment]
> > 我那个模型跑的时间太久了，想直接用已迭代的最好结果。不知道应该如何写入。谢谢老师，太麻烦老师了
> 
> 不可以，模型的结果依赖搜索的历史

终于跑完啦，谢谢老师！！！！十分感谢老师！！！！
