### ISSUE TITLE
经纬度坐标的设置和时间t的设置问题

### ISSUE THREAD

**Issue by TongCWei** [sunkun1997/mgtwr#9]
老师您好，请问经纬度坐标需要投影转换成m吗，假设时间从1980年的1月到2020年的12月，关于时间列t是从1开始吗

**Comment by sunkun1997** [comment]
时间是需要转换成整数或者浮点数的，因为要计算它们之间的差值

**Comment by sunkun1997** [comment]
经纬度你可以输入参数convert=True转换，时间是需要转换成整数或者浮点数的，因为要计算他们之间的差值

**Comment by TongCWei** [comment]
非常感谢老师您的及时回复。我想问这种转换是必须的吗，直接输入经纬度对结果以及运算速度的影响大吗，还有因为我的数据量比较大，有几十多万条，所以想问是否存在多线程等加速方法加速模型结果的输出的参数设置。

**Comment by sunkun1997** [comment]
建议转换，平面坐标才符合欧几里得公式；关于加速问题，你可以参照[pull requests](https://github.com/sunkun1997/mgtwr/pull/8)。但是mgtwr包还未来得及更新，你可以先git clone 这个仓

**Comment by TongCWei** [comment]
好嘞，谢谢老师
